### ISSUE TITLE
What's the font family used in the screenshots?

### ISSUE THREAD

**Issue by nNoidea** [BrianRuizy/material-kai#1]
Hi, what's the font family used in the screenshots?
I didn't know where else the ask the question (vscode marketplace send me here).

**Comment by BrianRuizy** [comment]
No worries, makes me consider opening a chat for discussions.
Here are the settings I configured for font family in VS Code, if that's what you're asking for :)


![image](https://user-images.githubusercontent.com/23439187/118877163-b6c5b880-b8b3-11eb-9fa6-27e0de3f7c91.png)
![image](https://user-images.githubusercontent.com/23439187/118877199-c1804d80-b8b3-11eb-8a25-7ceb19052cc7.png)

**Comment by BrianRuizy** [comment]
https://gitter.im/material-kai/community#
